export const TypeFormInput = [
  { key: "BLANK", value: "Blank" },
  { key: "TEXT", value: "Text" },
  { key: "TEXTAREA", value: "Text Area" },
  { key: "DATE", value: "Date" },
  { key: "DATETIME", value: "Date With Time" },
  { key: "TIME", value: "Time" },
  { key: "BOOL", value: "Boolean" },
  { key: "NUMERIC", value: "Numeric" },
  { key: "CURRENCY", value: "Currency" },
  { key: "PERCENT", value: "Percentage" },
  { key: "LOOKUP", value: "Lookup" },
  { key: "DDL", value: "Dropdownlist" },
  { key: "LABEL", value: "Label" },
  { key: "ADDRESS", value: "Address" },
]